
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title: loganblackstad.github.io
title_separator: '|'
name: 'Logan Blackstad'
description: 'A data analytics blog.'
url: null
baseurl: null
repository: null
teaser: /assets/images/teaser.jpg
words_per_minute: 200
comments:
    provider: null
    disqus:
        shortname: null
    discourse:
        server: null
    facebook:
        appid: null
        num_posts: null
        colorscheme: null
staticman:
    allowedFields:
        - name
        - email
        - url
        - message
    branch: master
    commitMessage: 'New comment.'
    filename: 'comment-{@timestamp}'
    format: yml
    moderation: true
    path: 'docs/_data/comments/{options.slug}'
    requiredFields:
        - name
        - email
        - message
    transforms:
        email: md5
    generatedFields:
        date:
            type: date
            options: {format: iso8601}
atom_feed:
    path: null
google_site_verification: null
bing_site_verification: null
alexa_site_verification: null
yandex_site_verification: null
twitter:
    username: null
facebook:
    username: null
    app_id: null
    publisher: null
og_image: null
social:
    type: null
    name: null
    links: null
analytics:
    provider: false
    google:
        tracking_id: null
author:
<<<<<<< HEAD
    name: 'Logan Blackstad'
    avatar: 'https://avatars0.githubusercontent.com/u/26091324'
    bio: 'Business & Data Analyst <br><br> <strong>Latest Project:</strong><br><a href=''https://loganblackstad.shinyapps.io/running-calc/'' style=''color:#000000''>''R Shiny Application - Road Running Pace Calculator''</a><br><br> <strong>Current Status:</strong> <br>1. Looking for a full-time Data Analyst position <br> 2. Growing my network <br>3. Learning new coding packages'
    location: 'Atlanta, GA'
    email: logan.blackstad@gmail.com
    uri: null
    bitbucket: null
    codepen: null
    dribbble: null
    flickr: null
    facebook: logan.blackstad
    foursquare: null
    github: loganblackstad
    google_plus: null
    keybase: null
    instagram: null
    lastfm: null
    linkedin: loganblackstad/
    pinterest: null
    soundcloud: null
    stackoverflow: null
    steam: null
    tumblr: null
    twitter: LoganBlackstad
    vine: null
    weibo: null
    xing: null
    youtube: null
=======
  name             : "Logan Blackstad"
  avatar           : https://avatars0.githubusercontent.com/u/26091324
  bio              : "Business & Data Analyst focused on storytelling through vizualization. <br><br> <strong>Latest Project:</strong><br><a href='https://loganblackstad.github.io/projects/' style='color:#000000'>Scraping Market Exchange Data to Create Base Metals Forecasts</a><br><br> <strong>Current Status:</strong> <br>1. Growing my network <br>2. Learning new packages <br>3. Always open to new opportunities"
  location         : "Atlanta, GA"
  email            : logan.blackstad@gmail.com
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : logan.blackstad
  foursquare       :
  github           : loganblackstad
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : loganblackstad/
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          : LoganBlackstad
  vine             :
  weibo            :
  xing             :
  youtube          :


# Reading Files
>>>>>>> parent of c458d79... Updated Sidebar in _config.yml; Added new Post for running calc
include:
    - .htaccess
    - _pages
exclude:
    - '*.sublime-project'
    - '*.sublime-workspace'
    - vendor
    - .asset-cache
    - .bundle
    - .jekyll-assets-cache
    - .sass-cache
    - assets/js/plugins
    - assets/js/_main.js
    - assets/js/vendor
    - Capfile
    - CHANGELOG
    - config
    - Gemfile
    - Gruntfile.js
    - gulpfile.js
    - LICENSE
    - log
    - node_modules
    - package.json
    - Rakefile
    - README
    - tmp
    - /docs
    - /test
keep_files:
    - .git
    - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n"
incremental: false
kramdown:
    input: GFM
    hard_wrap: false
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
    enable_coderay: false
sass:
    sass_dir: _sass
    style: compressed
permalink: '/:categories/:title/'
paginate: 8
paginate_path: '/page:num/'
timezone: null
gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-gist
    - jekyll-feed
    - jemoji
    - jekyll-archives
    - jekyll-jupyter-notebook
    - jekyll-toc
whitelist:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-gist
    - jekyll-feed
    - jemoji
category_archive:
    type: liquid
    path: /categories/
tag_archive:
    type: liquid
    path: /tags/
compress_html:
    clippings: all
    ignore:
        envs: development
defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            layout: single
            author_profile: true
            read_time: true
            comments: true
            share: true
            related: true
    -
        scope:
            path: ""
            type: pages
        values:
            layout: single
            author_profile: true
